/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIMain */

#ifndef _Included_jni_JNIMain
#define _Included_jni_JNIMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIMain
 * Method:    printJNIMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNIMain_printJNIMessage
  (JNIEnv *, jobject);

/*
 * Class:     jni_JNIMain
 * Method:    printJNIString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_JNIMain_printJNIString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
